version: "3.8"

networks:
  corp:
    driver: bridge

services:
  nest-server:
    container_name: nest-server
    build:
      context: ./apps/nest-server
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    ports:
      - 4939:4939
    environment:
      NODE_ENV: "development"
      PORT: 4939
    networks:
      - corp
    restart: on-failure

  react-client:
    container_name: react-client
    build:
      context: ./apps/react-client
      cache_from:
        - nginx:1.19.2
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    ports:
      - 4900:80
    environment:
      NODE_ENV: "development"
      PORT: 4900
    networks:
      - corp
    restart: on-failure
