version: "3.8"

networks:
  corp:
    driver: bridge

services:
  nest-server:
    container_name: nest-server
    build:
      context: ./apps/nest-server
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    ports:
      - 4949:4949
    environment:
      NODE_ENV: "development"
      PORT: 4949
    networks:
      - corp
    restart: on-failure
  redis-server:
    container_name: redis-server
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server



  #nextjs:
  #  build:
  #    context: ./apps/next-client
  #    dockerfile: ./Dockerfile
  #    args:      
  #      NODE_ENV: "development"
  #      BUILD_FLAG: ""

  #nginx:
  #  build: 
  #    context: ./apps/next-client/nginx
  #    dockerfile: ./Dockerfile
  #  ports:
  #    - 80:80

  # react-client:
  #   container_name: react-client
  #   build:
  #     context: ./apps/react-client
  #     cache_from:
  #       - nginx:1.19.2
  #     dockerfile: ./Dockerfile
  #     args:
  #       NODE_ENV: "development"
  #       BUILD_FLAG: ""
  #   ports:
  #     - 4900:80
  #   environment:
  #     NODE_ENV: "development"
  #     PORT: 4900
  #   networks:
  #     - corp
  #   restart: on-failure
